#!/usr/bin/env bash
set -e

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORTS_DIR="${ROOT_DIR}/tests/reports"

mkdir -p "${REPORTS_DIR}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

START_TIME=$(date +%s%N)

echo "============================================================"
echo "          CouncilAI Unified Test & Report Runner            "
echo "============================================================"
echo "Timestamp:   ${TIMESTAMP}"
echo "Reports Dir: ${REPORTS_DIR}"
echo "------------------------------------------------------------"

# 1. Go Backend Unit Tests
echo "[Step 1/2] Running Go Backend Unit Tests..."
cd "${ROOT_DIR}/services/go-backend"
go test -v -json ./... > "${REPORTS_DIR}/go_test_results.json"
echo "  ✓ Go unit tests passed cleanly (saved to: go_test_results.json)"

# 2. Python RAG Unit Tests
echo "[Step 2/2] Running Python RAG Unit Tests..."
cd "${ROOT_DIR}"
PYTHONPATH=services/python-rag python3 -m unittest discover services/python-rag/tests/ > "${REPORTS_DIR}/python_test_results.txt" 2>&1
echo "  ✓ Python RAG unit tests passed cleanly (saved to: python_test_results.txt)"

END_TIME=$(date +%s%N)
ELAPSED_NS=$((END_TIME - START_TIME))
ELAPSED_SEC=$(awk -v ns="$ELAPSED_NS" 'BEGIN { printf "%.3f", ns / 1000000000 }')

# Summary Report
SUMMARY_MD="${REPORTS_DIR}/latest_test_summary.md"
cat <<EOF > "${SUMMARY_MD}"
# CouncilAI Test & Benchmark Summary Report

**Execution Timestamp**: ${TIMESTAMP}
**Execution Duration**: ${ELAPSED_SEC}s

## Report Artifacts Generated
- **Go Unit & Integration Tests**: [go_test_results.json](file://${REPORTS_DIR}/go_test_results.json)
- **Python RAG Unit Tests**: [python_test_results.txt](file://${REPORTS_DIR}/python_test_results.txt)
- **k6 Load Test**: Run on-demand using \`k6 run tests/load/load_test.js\` (saves [k6_load_test_summary.json](file://${REPORTS_DIR}/k6_load_test_summary.json))

---
*Report automatically generated by \`scripts/run_tests_with_reports.sh\`.*
EOF

echo "------------------------------------------------------------"
echo "All unit tests completed cleanly in ${ELAPSED_SEC}s!"
echo "Summary report saved to: ${SUMMARY_MD}"
echo "============================================================"
