#!/usr/bin/env bash
set -e

# Directory paths
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORTS_DIR="${ROOT_DIR}/tests/reports"

mkdir -p "${REPORTS_DIR}"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "============================================================"
echo "          CouncilAI Unified Test & Report Runner            "
echo "============================================================"
echo "Timestamp: ${TIMESTAMP}"
echo "Reports Dir: ${REPORTS_DIR}"
echo "------------------------------------------------------------"

# 1. Go Backend Unit & Integration Tests
echo "[Step 1/3] Running Go Backend Unit Tests..."
cd "${ROOT_DIR}/services/go-backend"
go test -v -json ./... > "${REPORTS_DIR}/go_test_results.json" || true
echo "  ✓ Go test results saved to: ${REPORTS_DIR}/go_test_results.json"

# 2. Python RAG Unit Tests
echo "[Step 2/3] Running Python RAG Service Unit Tests..."
cd "${ROOT_DIR}"
if command -v pytest &> /dev/null; then
    pytest services/python-rag/tests/ --junitxml="${REPORTS_DIR}/pytest_results.xml" || true
    echo "  ✓ Pytest results saved to: ${REPORTS_DIR}/pytest_results.xml"
else
    echo "  ! Pytest not installed in current environment, skipping pytest XML generation."
fi

# 3. RAG Benchmark
echo "[Step 3/3] Running RAG Performance Benchmark..."
python3 "${ROOT_DIR}/tests/benchmarks/bench_rag.py" || true

# Summary Markdown Report
SUMMARY_MD="${REPORTS_DIR}/latest_test_summary.md"
cat <<EOF > "${SUMMARY_MD}"
# CouncilAI Test & Benchmark Summary Report

**Execution Timestamp**: ${TIMESTAMP}

## Report Artifacts Generated
- **Go Unit Tests**: [go_test_results.json](file://${REPORTS_DIR}/go_test_results.json)
- **Pytest Results**: [pytest_results.xml](file://${REPORTS_DIR}/pytest_results.xml)
- **RAG Benchmark**: [rag_benchmark_summary.json](file://${REPORTS_DIR}/rag_benchmark_summary.json)
- **k6 Load Test**: [k6_load_test_summary.json](file://${REPORTS_DIR}/k6_load_test_summary.json)

---
*Report automatically generated by `scripts/run_tests_with_reports.sh`.*
EOF

echo "------------------------------------------------------------"
echo "All tests finished! Summary report saved to:"
echo "  ${SUMMARY_MD}"
echo "============================================================"
